/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'seller' : IDL.Null,
  'buyer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'companyName' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GSTRate = IDL.Variant({
  'igst' : IDL.Float64,
  'cgstSgst' : IDL.Float64,
});
export const Time = IDL.Int;
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'verified' : IDL.Null,
    'cancelled' : IDL.Null,
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  }),
  'seller' : IDL.Principal,
  'timestamp' : Time,
  'gstRate' : GSTRate,
  'buyer' : IDL.Opt(IDL.Principal),
  'placeOfSupply' : IDL.Text,
  'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const ExternalEnergyReading = IDL.Record({
  'source' : IDL.Text,
  'gridImport' : IDL.Float64,
  'solarGeneration' : IDL.Float64,
  'timestamp' : Time,
  'batteryChargeLevel' : IDL.Float64,
  'appliancePowerUsage' : IDL.Float64,
  'gridExport' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEnergyReading' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignAdminRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'assignBuyerRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignSellerRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'calculateGST' : IDL.Func([IDL.Float64, GSTRate], [IDL.Float64], ['query']),
  'createInvoice' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        GSTRate,
        IDL.Variant({
          'verified' : IDL.Null,
          'cancelled' : IDL.Null,
          'paid' : IDL.Null,
          'sent' : IDL.Null,
          'rejected' : IDL.Null,
          'draft' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createInvoiceCaller' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        GSTRate,
        IDL.Variant({
          'verified' : IDL.Null,
          'cancelled' : IDL.Null,
          'paid' : IDL.Null,
          'sent' : IDL.Null,
          'rejected' : IDL.Null,
          'draft' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAppRole' : IDL.Func([IDL.Principal], [IDL.Opt(AppRole)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getLatestReadings' : IDL.Func(
      [],
      [IDL.Opt(ExternalEnergyReading)],
      ['query'],
    ),
  'getReadingsSince' : IDL.Func(
      [Time],
      [IDL.Vec(ExternalEnergyReading)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectInvoice' : IDL.Func([IDL.Text], [], []),
  'requestInvoiceModification' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInvoice' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'verified' : IDL.Null,
          'cancelled' : IDL.Null,
          'paid' : IDL.Null,
          'sent' : IDL.Null,
          'rejected' : IDL.Null,
          'draft' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'verifyInvoice' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'seller' : IDL.Null,
    'buyer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'companyName' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GSTRate = IDL.Variant({
    'igst' : IDL.Float64,
    'cgstSgst' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'verified' : IDL.Null,
      'cancelled' : IDL.Null,
      'paid' : IDL.Null,
      'sent' : IDL.Null,
      'rejected' : IDL.Null,
      'draft' : IDL.Null,
    }),
    'seller' : IDL.Principal,
    'timestamp' : Time,
    'gstRate' : GSTRate,
    'buyer' : IDL.Opt(IDL.Principal),
    'placeOfSupply' : IDL.Text,
    'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const ExternalEnergyReading = IDL.Record({
    'source' : IDL.Text,
    'gridImport' : IDL.Float64,
    'solarGeneration' : IDL.Float64,
    'timestamp' : Time,
    'batteryChargeLevel' : IDL.Float64,
    'appliancePowerUsage' : IDL.Float64,
    'gridExport' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEnergyReading' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignAdminRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'assignBuyerRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignSellerRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'calculateGST' : IDL.Func([IDL.Float64, GSTRate], [IDL.Float64], ['query']),
    'createInvoice' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          GSTRate,
          IDL.Variant({
            'verified' : IDL.Null,
            'cancelled' : IDL.Null,
            'paid' : IDL.Null,
            'sent' : IDL.Null,
            'rejected' : IDL.Null,
            'draft' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createInvoiceCaller' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          GSTRate,
          IDL.Variant({
            'verified' : IDL.Null,
            'cancelled' : IDL.Null,
            'paid' : IDL.Null,
            'sent' : IDL.Null,
            'rejected' : IDL.Null,
            'draft' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAppRole' : IDL.Func([IDL.Principal], [IDL.Opt(AppRole)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getLatestReadings' : IDL.Func(
        [],
        [IDL.Opt(ExternalEnergyReading)],
        ['query'],
      ),
    'getReadingsSince' : IDL.Func(
        [Time],
        [IDL.Vec(ExternalEnergyReading)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectInvoice' : IDL.Func([IDL.Text], [], []),
    'requestInvoiceModification' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInvoice' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'verified' : IDL.Null,
            'cancelled' : IDL.Null,
            'paid' : IDL.Null,
            'sent' : IDL.Null,
            'rejected' : IDL.Null,
            'draft' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'verifyInvoice' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };