/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'seller' : null } |
  { 'buyer' : null };
export interface ExternalEnergyReading {
  'source' : string,
  'gridImport' : number,
  'solarGeneration' : number,
  'timestamp' : Time,
  'batteryChargeLevel' : number,
  'appliancePowerUsage' : number,
  'gridExport' : number,
}
export type GSTRate = { 'igst' : number } |
  { 'cgstSgst' : number };
export interface Invoice {
  'id' : string,
  'status' : { 'verified' : null } |
    { 'cancelled' : null } |
    { 'paid' : null } |
    { 'sent' : null } |
    { 'rejected' : null } |
    { 'draft' : null },
  'seller' : Principal,
  'timestamp' : Time,
  'gstRate' : GSTRate,
  'buyer' : [] | [Principal],
  'placeOfSupply' : string,
  'items' : Array<[string, bigint]>,
}
export type Time = bigint;
export interface UserProfile {
  'appRole' : AppRole,
  'gstNumber' : [] | [string],
  'name' : string,
  'state' : [] | [string],
  'companyName' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEnergyReading' : ActorMethod<
    [number, number, number, number, number, string],
    undefined
  >,
  'assignAdminRole' : ActorMethod<[Principal, UserProfile], undefined>,
  'assignBuyerRole' : ActorMethod<[Principal, UserProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignSellerRole' : ActorMethod<[Principal, UserProfile], undefined>,
  'calculateGST' : ActorMethod<[number, GSTRate], number>,
  'createInvoice' : ActorMethod<
    [
      string,
      [] | [Principal],
      Array<[string, bigint]>,
      GSTRate,
      { 'verified' : null } |
        { 'cancelled' : null } |
        { 'paid' : null } |
        { 'sent' : null } |
        { 'rejected' : null } |
        { 'draft' : null },
      string,
    ],
    undefined
  >,
  'createInvoiceCaller' : ActorMethod<
    [
      string,
      [] | [Principal],
      Array<[string, bigint]>,
      GSTRate,
      { 'verified' : null } |
        { 'cancelled' : null } |
        { 'paid' : null } |
        { 'sent' : null } |
        { 'rejected' : null } |
        { 'draft' : null },
      string,
    ],
    undefined
  >,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAppRole' : ActorMethod<[Principal], [] | [AppRole]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoice' : ActorMethod<[string], [] | [Invoice]>,
  'getLatestReadings' : ActorMethod<[], [] | [ExternalEnergyReading]>,
  'getReadingsSince' : ActorMethod<[Time], Array<ExternalEnergyReading>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectInvoice' : ActorMethod<[string], undefined>,
  'requestInvoiceModification' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInvoice' : ActorMethod<
    [
      string,
      { 'verified' : null } |
        { 'cancelled' : null } |
        { 'paid' : null } |
        { 'sent' : null } |
        { 'rejected' : null } |
        { 'draft' : null },
    ],
    undefined
  >,
  'verifyInvoice' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];