/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Invoice {
    id: string;
    status: Variant_verified_cancelled_paid_sent_rejected_draft;
    seller: Principal;
    timestamp: Time;
    gstRate: GSTType;
    buyer?: Principal;
    placeOfSupply: string;
    items: Array<[string, bigint]>;
}
export type GSTType = {
    __kind__: "igst";
    igst: number;
} | {
    __kind__: "cgstSgst";
    cgstSgst: number;
};
export interface UserProfile {
    appRole: AppRole;
    gstNumber?: string;
    name: string;
    state?: string;
    companyName?: string;
}
export enum AppRole {
    admin = "admin",
    seller = "seller",
    buyer = "buyer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_verified_cancelled_paid_sent_rejected_draft {
    verified = "verified",
    cancelled = "cancelled",
    paid = "paid",
    sent = "sent",
    rejected = "rejected",
    draft = "draft"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignAdminRole(user: Principal, profile: UserProfile): Promise<void>;
    assignBuyerRole(user: Principal, profile: UserProfile): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignSellerRole(user: Principal, profile: UserProfile): Promise<void>;
    calculateGST(amount: number, gstType: GSTType): Promise<number>;
    createInvoice(id: string, buyer: Principal | null, items: Array<[string, bigint]>, gstRate: GSTType, pStatus: Variant_verified_cancelled_paid_sent_rejected_draft, placeOfSupply: string): Promise<void>;
    createInvoiceCaller(id: string, buyer: Principal | null, items: Array<[string, bigint]>, gstRate: GSTType, status: Variant_verified_cancelled_paid_sent_rejected_draft, placeOfSupply: string): Promise<void>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAppRole(user: Principal): Promise<AppRole | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInvoice(id: string): Promise<Invoice | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(user: Principal): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    rejectInvoice(id: string): Promise<void>;
    requestInvoiceModification(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateInvoice(id: string, pStatus: Variant_verified_cancelled_paid_sent_rejected_draft): Promise<void>;
    verifyInvoice(id: string): Promise<void>;
}
import type { AppRole as _AppRole, GSTType as _GSTType, Invoice as _Invoice, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignAdminRole(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAdminRole(arg0, to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAdminRole(arg0, to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignBuyerRole(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBuyerRole(arg0, to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBuyerRole(arg0, to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignSellerRole(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignSellerRole(arg0, to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignSellerRole(arg0, to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateGST(arg0: number, arg1: GSTType): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateGST(arg0, to_candid_GSTType_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateGST(arg0, to_candid_GSTType_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createInvoice(arg0: string, arg1: Principal | null, arg2: Array<[string, bigint]>, arg3: GSTType, arg4: Variant_verified_cancelled_paid_sent_rejected_draft, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_GSTType_n7(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n10(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_GSTType_n7(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n10(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createInvoiceCaller(arg0: string, arg1: Principal | null, arg2: Array<[string, bigint]>, arg3: GSTType, arg4: Variant_verified_cancelled_paid_sent_rejected_draft, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoiceCaller(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_GSTType_n7(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n10(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoiceCaller(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_GSTType_n7(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n10(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppRole(arg0: Principal): Promise<AppRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppRole(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppRole(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: string): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectInvoice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectInvoice(arg0);
            return result;
        }
    }
    async requestInvoiceModification(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestInvoiceModification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestInvoiceModification(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInvoice(arg0: string, arg1: Variant_verified_cancelled_paid_sent_rejected_draft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, to_candid_variant_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, to_candid_variant_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyInvoice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyInvoice(arg0);
            return result;
        }
    }
}
function from_candid_AppRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_GSTType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GSTType): GSTType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppRole]): AppRole | null {
    return value.length === 0 ? null : from_candid_AppRole_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        verified: null;
    } | {
        cancelled: null;
    } | {
        paid: null;
    } | {
        sent: null;
    } | {
        rejected: null;
    } | {
        draft: null;
    };
    seller: Principal;
    timestamp: _Time;
    gstRate: _GSTType;
    buyer: [] | [Principal];
    placeOfSupply: string;
    items: Array<[string, bigint]>;
}): {
    id: string;
    status: Variant_verified_cancelled_paid_sent_rejected_draft;
    seller: Principal;
    timestamp: Time;
    gstRate: GSTType;
    buyer?: Principal;
    placeOfSupply: string;
    items: Array<[string, bigint]>;
} {
    return {
        id: value.id,
        status: from_candid_variant_n14(_uploadFile, _downloadFile, value.status),
        seller: value.seller,
        timestamp: value.timestamp,
        gstRate: from_candid_GSTType_n15(_uploadFile, _downloadFile, value.gstRate),
        buyer: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.buyer)),
        placeOfSupply: value.placeOfSupply,
        items: value.items
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _AppRole;
    gstNumber: [] | [string];
    name: string;
    state: [] | [string];
    companyName: [] | [string];
}): {
    appRole: AppRole;
    gstNumber?: string;
    name: string;
    state?: string;
    companyName?: string;
} {
    return {
        appRole: from_candid_AppRole_n19(_uploadFile, _downloadFile, value.appRole),
        gstNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.gstNumber)),
        name: value.name,
        state: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.state)),
        companyName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.companyName))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    cancelled: null;
} | {
    paid: null;
} | {
    sent: null;
} | {
    rejected: null;
} | {
    draft: null;
}): Variant_verified_cancelled_paid_sent_rejected_draft {
    return "verified" in value ? Variant_verified_cancelled_paid_sent_rejected_draft.verified : "cancelled" in value ? Variant_verified_cancelled_paid_sent_rejected_draft.cancelled : "paid" in value ? Variant_verified_cancelled_paid_sent_rejected_draft.paid : "sent" in value ? Variant_verified_cancelled_paid_sent_rejected_draft.sent : "rejected" in value ? Variant_verified_cancelled_paid_sent_rejected_draft.rejected : "draft" in value ? Variant_verified_cancelled_paid_sent_rejected_draft.draft : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    igst: number;
} | {
    cgstSgst: number;
}): {
    __kind__: "igst";
    igst: number;
} | {
    __kind__: "cgstSgst";
    cgstSgst: number;
} {
    return "igst" in value ? {
        __kind__: "igst",
        igst: value.igst
    } : "cgstSgst" in value ? {
        __kind__: "cgstSgst",
        cgstSgst: value.cgstSgst
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    seller: null;
} | {
    buyer: null;
}): AppRole {
    return "admin" in value ? AppRole.admin : "seller" in value ? AppRole.seller : "buyer" in value ? AppRole.buyer : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n12(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_GSTType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GSTType): _GSTType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: AppRole;
    gstNumber?: string;
    name: string;
    state?: string;
    companyName?: string;
}): {
    appRole: _AppRole;
    gstNumber: [] | [string];
    name: string;
    state: [] | [string];
    companyName: [] | [string];
} {
    return {
        appRole: to_candid_AppRole_n3(_uploadFile, _downloadFile, value.appRole),
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        state: value.state ? candid_some(value.state) : candid_none(),
        companyName: value.companyName ? candid_some(value.companyName) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_verified_cancelled_paid_sent_rejected_draft): {
    verified: null;
} | {
    cancelled: null;
} | {
    paid: null;
} | {
    sent: null;
} | {
    rejected: null;
} | {
    draft: null;
} {
    return value == Variant_verified_cancelled_paid_sent_rejected_draft.verified ? {
        verified: null
    } : value == Variant_verified_cancelled_paid_sent_rejected_draft.cancelled ? {
        cancelled: null
    } : value == Variant_verified_cancelled_paid_sent_rejected_draft.paid ? {
        paid: null
    } : value == Variant_verified_cancelled_paid_sent_rejected_draft.sent ? {
        sent: null
    } : value == Variant_verified_cancelled_paid_sent_rejected_draft.rejected ? {
        rejected: null
    } : value == Variant_verified_cancelled_paid_sent_rejected_draft.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    admin: null;
} | {
    seller: null;
} | {
    buyer: null;
} {
    return value == AppRole.admin ? {
        admin: null
    } : value == AppRole.seller ? {
        seller: null
    } : value == AppRole.buyer ? {
        buyer: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "igst";
    igst: number;
} | {
    __kind__: "cgstSgst";
    cgstSgst: number;
}): {
    igst: number;
} | {
    cgstSgst: number;
} {
    return value.__kind__ === "igst" ? {
        igst: value.igst
    } : value.__kind__ === "cgstSgst" ? {
        cgstSgst: value.cgstSgst
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
